# Generated by Django 5.1.5 on 2025-01-29 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0005_faculty'),
        ('University', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_active', models.BooleanField(default=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_registration_required', models.BooleanField(default=False)),
                ('is_registration_free', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.college')),
            ],
        ),
    ]
