# Generated by Django 5.1.5 on 2025-01-29 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0006_event'),
        ('University', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('skills_required', models.TextField()),
                ('application_deadline', models.DateTimeField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='placements/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.college')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
