# Generated by Django 5.1.5 on 2025-01-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0007_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
