# Generated by Django 5.1.5 on 2025-01-30 05:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0008_event_registration_fee'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_paid', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.student')),
            ],
        ),
    ]
