# Generated by Django 5.1.5 on 2025-02-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_university'),
        ('College', '0008_event_registration_fee'),
        ('Student', '0002_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(help_text='Upload PDF, Word, or Image', upload_to='notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.university')),
            ],
        ),
    ]
